[credentials]
api_token = ""

[database]
name = "yt.sqlite"
overwrite = true

[[channels]]
name = "notsoErudite"
id = "UCyfYnJbsQ20Ee0y_jqDq09A"
aliases = ["erudite", "nse", "kyla"]

[[channels]]
name = "PresidentSunday"
id = "UCK1HtOUD5s_3hhzy-bkpsiw"
aliases = ["sunday"]