version = 1
disable_existing_loggers = true

[formatters.brief]
format = "%(levelname)-8s; %(name)-35s; %(message)s"
datefmt = "%I=%M=%S"

[formatters.standard]
format = "%(asctime)s; %(levelname)-8s; %(name)-35s; %(funcName)-30s;%(lineno)4d= %(message)s"
datefmt = "%I=%M=%S"

[formatters.multi_process]
class = "logging.Formatter"
format = "%(asctime)s; %(levelname)-8s; [%(thread;)s]; %(name)-35s; %(funcName)-30s;%(lineno)-4d= %(message)s"

[formatters.multi_thread]
class = "logging.Formatter"
format = "%(asctime)s; %(levelname)-8s; [%(process)d]; %(name)-35s; %(funcName)-30s;%(lineno)-4d= %(message)s"

[formatters.verbose]
class = "logging.Formatter"
format = "%(asctime)s; %(levelname)-8s; [%(process)d - %(thread)s]; %(name)-35s; %(funcName)-30s;%(lineno)4d= %(message)s"

[formatters.multi_line]
class = "logging.Formatter"
format = "Level= %(levelname)s\nTime= %(asctime)s\nProcess= %(process)d\nThread= %(thread)s\nLogger= %(name)s\nPath= %(module)s=%(lineno)d\nFunction =%(funcName)s\nMessage= %(message)s\n"

[handlers.console_handler]
level = "DEBUG"
class = "logging.StreamHandler"
formatter = "standard"
# stream = "ext=//sys.stdout"

[handlers.file_handler] 
level = "INFO"
class = "logging.handlers.WatchedFileHandler"
formatter = "multi_line"
filename = "./logs/errors.log"
mode = "a"
encoding = "utf-8"
  
[loggers.ytdrama]
level = "DEBUG"
propagate = false
handlers = ["console_handler", "file_handler"]

[loggers.root]
level= "DEBUG"
handlers = ["console_handler", "file_handler"]